config/routes.rb
School::Application.routes.draw do
  resources :attendances

  resources :teachers

  resources :students do
    member do
      get 'activate'
    end    
  end

  resources :classrooms do 
    member do
      get 'actives'
    end
  end
  
  root :to => "home#index"

  devise_for :users

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  validates :name, :presence => true,:uniqueness => true
  has_many :students    
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @classrooms }
      format.xml { render xml: @classrooms }
    end
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @classroom }
      format.xml { render xml: @classroom }
    end
  end

  # GET /classrooms/new
  # GET /classrooms/new.json
  def new
    @classroom = Classroom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @classroom }
      format.xml { render xml: @classroom }
    end
  end

  # GET /classrooms/1/edit
  def edit
    @classroom = Classroom.find(params[:id])
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(params[:classroom])

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render json: @classroom, status: :created, location: @classroom }
        format.xml { render xml: @classroom, status: :created, location: @classroom }
      else
        format.html { render action: "new" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
        format.xml  { render xml: @classroom.errors, status:  :unprocessable_entity }
      end
    end
  end

  # PUT /classrooms/1
  # PUT /classrooms/1.json
  def update
    @classroom = Classroom.find(params[:id])

    respond_to do |format|
      if @classroom.update_attributes(params[:classroom])
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { head :ok }
        format.xml  { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
        format.xml  { render xml: @classroom.errors, status:  :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom = Classroom.find(params[:id])
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url }
      format.json { head :ok }
      format.xml  { head :ok }
    end
  end
  
  def actives
    @students = Student.actives(params[:id])
  end
  
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<br/>
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br/>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :strength %><br />
    <%= f.number_field :strength %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classrooms/actives.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Class</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.phone %></td>
    <td><%= student.classroom.name %></td>
    <td><%= student.active ? "Yes" : "No" %></td>
    <td><%= link_to 'Show', student %></td>
    <td> | <%= link_to 'Edit', edit_student_path(student) %></td>
    <td> | <%= link_to 'Mark Attendence', new_attendance_path(:id => student, :type => "Student") %></td>
<td> | <%= link_to "#{student.active ? 'Deactivate' : 'Activate' }", activate_student_path(student) %></td>
    <td> | <%= link_to 'Destroy', student, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<h1>Listing classrooms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Strength</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @classrooms.each do |classroom| %>
  <tr>
    <td><%= classroom.name %></td>
    <td><%= classroom.strength %></td>
    <td><%= link_to 'Show', classroom %> </td>
    <td> | <%= link_to 'Edit', edit_classroom_path(classroom) %> </td>
    <td> | <%= link_to 'Show Active Students', actives_classroom_path(classroom) %> </td>
    <td> | <%= link_to 'Destroy', classroom, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= render 'form' %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p>
  <b>Name:</b>
  <%= @classroom.name %>
</p>

<p>
  <b>Strength:</b>
  <%= @classroom.strength %>
</p>


<%= link_to 'Edit', edit_classroom_path(@classroom) %> |
<%= link_to 'Back', classrooms_path %>