config/routes.rb
School::Application.routes.draw do
  resources :attendances

  resources :teachers

  resources :students do
    member do
      get 'activate'
    end    
  end

  resources :classrooms do 
    member do
      get 'actives'
    end
  end
  
  root :to => "home#index"

  devise_for :users

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :attendable, :polymorphic => true
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  # GET /attendances
  # GET /attendances.json
  before_filter :get_attendes, :only =>[:create, :new]
  def index
    @attendances = Attendance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attendances }
    end
  end

  # GET /attendances/new
  # GET /attendances/new.json
  def new
    @attendance = Attendance.new
    #raise @attendable.inspect
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @attendance }
    end
  end

  # GET /attendances/1/edit
  def edit
    @attendance = Attendance.find(params[:id])
  end

  # POST /attendances
  # POST /attendances.json
  def create
    #raise @attendable.inspect
    @attendance = @attendable.attendances.new(params[:attendance])

    #respond_to do |format|
      if @attendance.save
        redirect_to attendances_path, notice: 'Attendance was successfully created.'
        
      else
#        format.html { render action: "new" }
#        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    #end
  end

  # PUT /attendances/1
  # PUT /attendances/1.json
  def update
    @attendance = Attendance.find(params[:id])

    respond_to do |format|
      if @attendance.update_attributes(params[:attendance])
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url }
      format.json { head :ok }
    end
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_form.html.erb
<%#= form_for :url => attendance_path(@attendance,:type=> "whtever"),:html=> {:method => :post} do |f| %>

<%#= form_for @attendance, :url => object_path(@object, :type => "whtever"), :html => {:method => :post} do |f| %>

<%= form_for @attendance,
             :url => { :controller => :attendances,
                       :action => :create,
                       :type => params[:type], :id=>params[:id] } do |f| %>
  <% if @attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% @attendance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :time_in %><br />
    <%= f.datetime_select :time_in %>
  </div>
  <div class="field">
    <%= f.label :time_out %><br />
    <%= f.datetime_select :time_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

app/views/attendances/index.html.erb
<h1>Listing attendances</h1>

<table>
  <tr>
    <th>Time in(mm-dd-yy hrs:mins)</th>
    <th>Time out(mm-dd-yy hrs:mins)</th>
    <th>Attendence For</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendances.each do |attendance| %>
  <tr>
    <td><%= attendance.time_in.strftime("%m-%d-%Y %H:%M") %></td>
    <td><%= attendance.time_out.strftime("%m-%d-%Y %H:%M") %></td>
<td><%= attendance.attendable_type %></td>
<td><%= attendance.attendable.name %></td>
    <td><%= link_to 'Show', attendance %></td>
    <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
    <td><%= link_to 'Destroy', attendance, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render 'form' %>

<%= link_to 'Back', attendances_path %>

app/views/attendances/show.html.erb
<p>
  <b>Time in:</b>
  <%= @attendance.time_in.strftime("%m-%d-%Y %H:%M") %>
</p>

<p>
  <b>Time out:</b>
  <%= @attendance.time_out.strftime("%m-%d-%Y %H:%M") %>
</p>


<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>